services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn ChatProject.wsgi:application --bind 0.0.0.0:$PORT &
      daphne ChatProject.asgi:application -b 0.0.0.0 -p 8001
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: ChatProject.settings
      - key: PORT
        value: 8000